# Generated by Django 3.2.18 on 2023-11-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('confessionID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=400)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='confessions.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='confessions.user')),
            ],
        ),
    ]
