# Generated by Django 4.2.7 on 2024-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='message',
        ),
        migrations.AddField(
            model_name='confession',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confession',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
