# Generated by Django 4.2.7 on 2024-11-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('report', models.TextField(default='')),
                ('confession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession', to='confessions.confession')),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_id', to='confessions.user')),
            ],
        ),
    ]
