# Generated by Django 4.2.7 on 2024-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_remove_confession_message_confession_bookmarked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
