# Generated by Django 4.2.7 on 2024-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0003_confession_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('verification_code', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
