# Generated by Django 4.2.7 on 2024-07-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0004_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SavedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='confessions.user')),
            ],
        ),
    ]
