# Generated by Django 4.2.7 on 2024-08-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0005_alter_emailverification_createdat_saveduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confession',
            options={'ordering': ['dateTime']},
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField(default='')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='confessions.user')),
            ],
        ),
    ]
