# Generated by Django 4.2.7 on 2024-08-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0006_alter_confession_options_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('reviewer', models.EmailField(max_length=250)),
                ('rating', models.IntegerField()),
                ('detail', models.TextField(default='')),
            ],
        ),
    ]
